# Generated by Django 4.1.3 on 2023-11-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dict',
            old_name='order_id',
            new_name='work_order',
        ),
    ]
