# Generated by Django 4.1.3 on 2023-11-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debugdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('debugdata_id', models.IntegerField(default=0, help_text='调试数据表ID', verbose_name='调试数据表ID')),
                ('testStepNo', models.CharField(help_text='测试步骤编号', max_length=30, verbose_name='测试步骤编号')),
                ('testStepName', models.CharField(help_text='测试步骤名称', max_length=150, verbose_name='测试步骤名称')),
                ('testStepResult', models.CharField(help_text='测试步骤结果', max_length=150, verbose_name='测试步骤结果')),
            ],
            options={
                'verbose_name': '调试数据_测试步骤',
                'verbose_name_plural': '调试数据_测试步骤',
                'db_table': 'django_debugdata_teststep',
            },
        ),
    ]
